### ISSUE TITLE
question: Get button number from device event

### ISSUE THREAD

**Issue by jimmyfortinx** [SmartThingsCommunity/smartapp-sdk-nodejs#155]
**What is your question? Please describe.**
Is it possible to get the button number that triggered an event? 

**Additional context**
I have a Z-Wave switch that requires a device handler written in Groovy. When I wrote SmartApps with Groovy it was possible to get the button number, but now when I subscribe to device event I don't receive that data.

I'm requesting for a device with the button capability like that:
```ts
section
        .deviceSetting("armingButton")
        .capabilities(["button"])
        .submitOnChange(true);
```

I'm subscribing to the device event that way:
```ts
.updated(async (context) => {
    await context.api.subscriptions.unsubscribeAll();
    await Promise.all([
      context.api.subscriptions.subscribeToDevices(
        context.config.armingButton,
        "*",
        "*",
        "armingButtonEventHandler"
      ),
    ]);
  })
.subscribedDeviceEventHandler(
    "armingButtonEventHandler",
    async (context, deviceEvent) => {
      const buttons = await context.configDevicesWithState("armingButton");

      console.log(deviceEvent, buttons[0].state);
    }
  )
```

I received this under deviceEvent:

```js
{
  eventId: '...',
  locationId: '...',
  deviceId: '...',
  componentId: 'main',
  capability: 'holdableButton',
  attribute: 'button',
  value: 'pushed',
  valueType: 'string',
  stateChange: true,
  data: {},
  subscriptionName: 'armingButtonEventHandler_0'
}
```

But I can see the `numberOfButtons` value when I do `context.configDevicesWithState("armingButton")`:

```js
{
...
  button: {
    button: { value: 'pushed', timestamp: '2020-08-09T23:34:36.578+0000' },
    numberOfButtons: { value: 8, timestamp: '2019-12-27T00:30:15.142+0000' },
    supportedButtonValues: { value: null, timestamp: '2020-06-24T10:52:38.656+0000' }
  },
...
}
```

Is that a feature missing to support old device handler?

**Comment by bflorian** [comment]
@jimmyfortinx I'm following up on this issue with the appropriate. The data field was omitted from the event intentionally in favor of using multiple components to represent the different buttons, but we may need to reconsider that approach since all multi-button devices won't change at the same time. Which Z-Wave switch are you using that has 8 buttons?

**Comment by jimmyfortinx** [comment]
@bflorian I'm using the LZW31-SN from Inovelli which does multiple buttons by multiple tap on up or down button + quick action button.

Thanks for the follow-up

https://inovelli.com/red-series-dimmer-switch-z-wave/

https://community.inovelli.com/t/how-to-lzw31-sn-red-series-dimmer-switch-setup-smartthings/989

**Comment by bflorian** [comment]
The `data.buttonNumber` property in the button capability was omitted because we are migrating to an approach where multiple buttons are represented by different component IDs in the new event structure. The SmartThings platform team is currently investigating a change that will automatically map the `data.buttonNumber` property to a corresponding componentId without having to modify the DTHs. I'll post more details here when they become available.

@jimmyfortinx in the specific case of the Inovelli Dimmer scene control gestures, a different solution is in progress.  The custom DTH for that device maps different gestures to different button numbers because at the time it was written, the button capability only supported the "pressed" and "held" gestures. However, the button capability was subsequently changed to directly support gestures such as up, up 2x, up 3x, etc., which will allow that device to be modeled without resorting to multiple button components. An updated DTH is in the process of being certified (see the above DTH reference). Once that is deployed, all the various scene control gestures for this device will be available in app event subscriptions as well as the rule builder on the new SmartThings App.

**Comment by jimmyfortinx** [comment]
@bflorian Great, thanks for the info. Really appreciated.
