### ISSUE TITLE
Can't subscribe 'deviceLifecycle' in lambda

### ISSUE THREAD

**Issue by solmar36** [SmartThingsCommunity/smartapp-sdk-nodejs#164]
**Describe the bug**

When I use below api inside installed lifecycle step in **lambda**(smartapp.handleLambdaCallback(event, context, callback)), below error occurs and the lifecycle gets 500 error. 
`await context.api.subscriptions.subscribeToDeviceLifecycle('deviceLifecycle')`
```
Error: Request failed with status code 403
at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:236:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**To Reproduce**

**Expected behavior**
: Could subscribe 'deviceLifecycle' also in lambda handler and therefore, smartapp could get device create, update, delete events. 

**Actual behavior**
A clear and concise description of what actually happens.
https://github.com/bflorian/smartthings-core-sdk/blob/5a7b909b0e1bbfb65e41b723b2cf960e67afe8e6/src/endpoint/subscriptions.ts#L423
-> Gets upper error

**Additional context**

**Comment by bflorian** [comment]
@solmar36 the 403 response suggests a permissions issue. Make sure that your app includes the `r:devices:*` scope and that you explicitly request that scope in the CONFIGURATION/INITIALIZE response with something like the following code:
```
const smartApp = new SmartApp()
    .permissions(['r:devices:*'])
```
You don't need to explicitly request the scope to access individual devices selected in configuration pages, but you do in order to subscribe to the health events of all devices (or to subscribe to all devices by capability). 

If you are already requesting this permission explicitly let me know, and we will investigate further.

**Comment by solmar36** [comment]
Thank you, it works with the permission you've suggested (as you already knew, it was not related to lambda). I have one more issue left but I'll make it with a separate page. Thanks again for your help.
